/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/modelsmodels/Office.gltf -k 
*/

import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { animate, useMotionValue } from "framer-motion";
import { motion } from "framer-motion-3d";
import { useFrame } from "@react-three/fiber";

export function Office(props) {
  const { section } = props;

  // const { nodes, materials } = useGLTF("/models/Office.gltf");
  // const texture = useTexture("textures/baked_Office.jpg");
  const { nodes, materials } = useGLTF("/models/Office_with_screens.gltf");
  const texture = useTexture("/textures/baked_with_screens_4k.png");
  const textureVSCode = useVideoTexture("/textures/vscode.mp4");

  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  const textureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0, { duration: 0.8 });
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
  });

  return (
    // <group {...props} dispose={null}>
    //   <mesh
    //     name="floor"
    //     geometry={nodes.floor.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="rug"
    //     geometry={nodes.rug.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="tree"
    //     geometry={nodes.tree.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="houseplant"
    //     geometry={nodes.houseplant.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="toy_plane"
    //     geometry={nodes.toy_plane.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="table_toy"
    //     geometry={nodes.table_toy.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <motion.mesh
    //     scale={[0, 0, 0]}
    //     animate={{
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //     name="books"
    //     geometry={nodes.books.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="shelf"
    //     geometry={nodes.shelf.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="chair"
    //     geometry={nodes.chair.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="vr"
    //     geometry={nodes.vr.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="speaker"
    //     geometry={nodes.speaker.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="pc"
    //     geometry={nodes.pc.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="keyboard"
    //     geometry={nodes.keyboard.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="side_right"
    //     geometry={nodes.side_right.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="side_left"
    //     geometry={nodes.side_left.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="mouse"
    //     geometry={nodes.mouse.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="mousepad"
    //     geometry={nodes.mousepad.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="tablet"
    //     geometry={nodes.tablet.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="table"
    //     geometry={nodes.table.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    //   <mesh
    //     name="monitor"
    //     geometry={nodes.monitor.geometry}
    //     material={textureMaterial}
    //     position={[0.019, 0.559, -1.5]}
    //     rotation={[-Math.PI, 0.321, -Math.PI]}
    //   />
    // </group>

    <group {...props} dispose={null}>
      <mesh
        name="floor"
        geometry={nodes.floor.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
        scale={0.016}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="rug"
        geometry={nodes.rug.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="houseplant"
        geometry={nodes.houseplant.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="books"
        geometry={nodes.books.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="shelf"
        geometry={nodes.shelf.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="toy_plane"
        geometry={nodes.toy_plane.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="shelf_toy"
        geometry={nodes.shelf_toy.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <motion.mesh
        scale={0.016}
        animate={{ scale: section === 0 ? 0.016 : 0 }}
        name="tree"
        geometry={nodes.tree.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="table"
        geometry={nodes.table.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="PC"
        geometry={nodes.PC.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="speaker"
        geometry={nodes.speaker.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="vr"
        geometry={nodes.vr.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="sideLeft"
        geometry={nodes.sideLeft.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="sideRight"
        geometry={nodes.sideRight.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="mouse"
        geometry={nodes.mouse.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="keyboard"
        geometry={nodes.keyboard.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="monitor"
        geometry={nodes.monitor.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="tab"
        geometry={nodes.tab.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="mousepad"
        geometry={nodes.mousepad.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="chair"
        geometry={nodes.chair.geometry}
        material={textureMaterial}
        position={[0.016, 0, 0.599]}
      />
      <mesh
        scale={0.016}
        name="monitor_screen"
        geometry={nodes.monitor_screen.geometry}
        position={[0.016, 0, 0.599]}
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>
      <mesh
        scale={0.016}
        name="tab_screen"
        geometry={nodes.tab_screen.geometry}
        position={[0.016, 0, 0.599]}
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Office_with_screens.gltf");
useTexture.preload("/textures/baked_with_screens_4k.png");
